# Generated by Django 5.0.7 on 2024-07-28 18:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_rename_orden_orderproduct_order'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderproduct',
            old_name='quatity',
            new_name='quantity',
        ),
    ]
